# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

# If not running interactively, don't do anything
[ -z "$PS1" ] && return
PS1="\u@\h:\W$ \[\e]2;\u@\H \w\a"

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# add color to a few commands
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='rgrep --color=auto'

# some ls aliases
alias ls='ls --color=auto'
alias lal='ls -al'
alias lla='ls -la'
alias ll='ls -l'
alias la='ls -a'
alias l='ls'

# ssh alias
alias aml='ssh aml.cs.byu.edu'
alias savant='ssh aml.cs.byu.edu -t ssh savant'
alias coherence='ssh aml.cs.byu.edu -t ssh coherence'
alias entropy='ssh entropy.cs.byu.edu'

# enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# I always want color
export TERM="xterm-256color"

# All other cli editors suck
export EDITOR="vim"

# some nifty functions and aliases

function python {
    if [ $# = 0 ]
    then
        ipython || /usr/bin/python
    else
        /usr/bin/python "$@"
    fi
}

function cdls()
{
    if [ $# = 0 ]
    then
        cd
    else
        cd "$@"
    fi
    ls
}
alias cd='cdls'

function greper()
{
    grep -r --include="$1" $2 .
}

alias untar='tar -xf'
