# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files for examples

# Set up some paths
if [[ ! "$PATH" =~ (^|:)"$HOME/.local/bin"(:|$) ]]
then
    export PATH="$PATH":"$HOME/.local/bin"
fi
if [[ ! "$PATH" =~ (^|:)"$HOME/go/bin"(:|$) ]]
then
    export PATH="$PATH":"$HOME/go/bin"
fi
export GOPATH=$HOME/go

# If not running interactively, don't do anything else
[ -z "$PS1" ] && return
PS1="\u@\h:\W$ \[\e]2;\u@\H \w\a"

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=100000

# make bash history ignore common commands I ever won't search for
export HISTIGNORE="&:ls:ll:la:cd:cd *:clear:vim:git st:git wipe"

# check the window size after each command and update values LINES and COLUMNS
shopt -s checkwinsize

# the pattern "**" used in pathnames will match all files in subdirectories
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# add color to a grep commands
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='rgrep --color=auto'

# some ls aliases
alias ls='ls --color=auto'
alias lal='ls -al'
alias lla='ls -la'
alias ll='ls -l'
alias la='ls -a'
alias l='ls'

# ssh aliases
alias aml='ssh aml.cs.byu.edu'
alias savant='ssh aml.cs.byu.edu -t ssh savant'
alias coherence='ssh aml.cs.byu.edu -t ssh coherence'
alias marylou='ssh ssh.fsl.byu.edu'
alias fsl='ssh ssh.fsl.byu.edu'
alias schizo='ssh sczhio.cs.byu.edu'

# enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# I always want color
export TERM="xterm-256color"

# All other cli editors suck
export EDITOR="vim"

# some nifty functions and aliases

function python {
    if [ $# = 0 ]
    then
        ipython || /usr/bin/python
    else
        /usr/bin/python "$@"
    fi
}

function cdls()
{
    if [ $# = 0 ]
    then
        cd
    else
        cd "$@"
    fi
    ls
}
alias cd='cdls'

function lc()
{
    find | grep \\.$1$ | xargs wc -l | sort -b -g
}

function clean()
{
    if [ $# -eq 0 ]; then
        echo "Must supply extension"
    else
        for file in $(find | grep \\.$1$); do
            echo "Removing $file"
            rm $file
        done
    fi
}

function repeat()
{
    while true; do
        $@
    done
}

alias untar='tar -xf'
alias todo='grep -nr "TODO\|FIXME\|XXX" *'
alias browse='pcmanfm .'

function brightness()
{
    sudo bash -c "echo $1 > /sys/class/backlight/acpi_video0/brightness"
}

# Insecure ssh aliases
alias issh="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null"
alias ipssh="pssh -x '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o GlobalKnownHostsFile=/dev/null'"
