" First, be iMproved
set nocompatible

" Plugins load faster with this off
filetype off

" Load plugins via Vundle
set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'Valloric/YouCompleteMe'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'drmingdrmer/vim-syntax-markdown'
Plugin 'fatih/vim-go'
Plugin 'garbas/vim-snipmate'
Plugin 'gmarik/Vundle.vim'
Plugin 'jlund3/colorschemer'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'mileszs/ack.vim'
Plugin 'noahfrederick/vim-skeleton'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'scrooloose/syntastic'
Plugin 'tomtom/tlib_vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-repeat'
call vundle#end()

" Turn on file type based options
syntax on
filetype on
filetype indent on
filetype plugin on
let g:tex_flavor="latex"

" Turn on a few more options
set title
set backspace=2
set scrolloff=2
set showcmd
set showmode
set guioptions=ace
set colorcolumn=81
set number
set relativenumber
set wrap
set ttyfast

" Even more options for vsplits
set winwidth=84
autocmd WinEnter * setlocal number relativenumber wrap
autocmd WinLeave * setlocal nonumber norelativenumber nowrap

" In memory buffers
set nobackup
set noswapfile
set hidden

" Switch up the colors
set t_Co=256
set t_ut=
silent! colorscheme lucid

" Setup statusline
set laststatus=2
set statusline=%<
set statusline+=%t
set statusline+=\ %([%Y%R%H%W]%)
set statusline+=%m
set statusline+=%{fugitive#statusline()}
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=\ %{&spell?\"SPELL\ \":\"\"}
set statusline+=%{&paste?\"PASTE\ \":\"\"}
set statusline+=%{&scrollbind?\"SCROLLBIND\":\"\"}
set statusline+=%=
set statusline+=%-14.(%l,%v%)
set statusline+=\ %P

" Setup cursorline
autocmd WinEnter * setlocal cursorline
autocmd BufEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
setlocal cursorline

" More sane split openings
set splitbelow
set splitright

" Set the leader keys
let mapleader=" "
let maplocalleader="-"

" Better whitespace
set list listchars=tab:»\ ,trail:·,nbsp:·
set expandtab
set textwidth=79
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent

" Handle trailing whitespace
function! StripTrailingWhitespace()
    let l=line(".")
    let c=col(".")
    execute '%s/\(\s\|\)\+$//e'
    call cursor(l, c)
endfunction
nnoremap <silent> <leader><space> :call StripTrailingWhitespace()<cr>

" Setup search
set hlsearch
set incsearch
set ignorecase
set smartcase
nnoremap <silent> <leader>/ :nohlsearch<cr>

" Setup NERDTree
nnoremap <silent> <leader>n :NERDTreeToggle<cr>
let NERDTreeIgnore=[]
let NERDTreeIgnore+=['\.pyc$', '__pycache__']
let NERDTreeIgnore+=['\.o$', '\.d$']
let NERDTreeIgnore+=['\.aux$', '\.log$']
let NERDTreeIgnore+=['\.class$']
let NERDTreeIgnore+=['\.make$', '\.blg$', '\.bbl$', '\.fls$', '\.cookie$']
let NERDTreeQuitOnOpen=1
let NERDTreeChDirMode=2

" Setup CtrlP
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn)$',
    \ 'file': '\v\.(pyc|blg|bbl|fls|cookies|make|o|d|class|aux|log)$',
    \ }
let g:ctrlp_working_path_mode = 'a'

" Setup Tagbar
nnoremap <silent> <leader>t :TagbarToggle<cr>
let g:tagbar_autoclose=1
let g:tagbar_left=1
let g:tagbar_sort=0

" Setup YouCompleteMe
let g:ycm_autoclose_preview_window_after_insertion=1
let g:ycm_key_list_select_completion=[]
let g:ycm_key_list_previous_completion=[]
let g:ycm_server_log_level='error'
let g:ycm_key_detailed_diagnostics=''
let g:ycm_server_python_interpreter='/usr/bin/python3'

" Setup Syntastic
let g:syntastic_check_on_open = 1
let g:syntastic_python_pylint_exe = 'python3 -m pylint'

" Setup ack.vim
let g:ack_autoclose=1
nnoremap <leader>a :Ack <c-r><c-w><cr>
nnoremap <silent> <leader>d :Ack "TODO\|FIXME\|XXX"<cr>
com TODO Ack TODO\|FIXME\|XXX

" Setup vim-tmux-navigator
let g:tmux_navigator_no_mappings=1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>

" Setup vim-go
let g:go_doc_keywordprg_enabled=0
let g:go_def_mapping_enabled=0
let g:go_textobj_enabled=0

" Setup vim-skeleton
let g:skeleton_replacements = {}
function! g:skeleton_replacements.PACKNAME()
    return expand('%:p:h:t')
endfunction
autocmd BufReadPost *
    \ if line('$') == 1 && getline('$') == '' && filewritable(expand('%')) == 1
    \ | SkelInsert! | write
    \ | endif

" Navigation shortcuts
nnoremap <s-j> <c-f>zz
nnoremap <s-k> <c-u>zz
vnoremap <s-j> <c-f>zz
vnoremap <s-k> <c-u>zz
nnoremap j gj
nnoremap k gk

" Simplfy toggling a flag
function! ToggleFlag(option, flag)
    exec ('let lopt = &' . a:option)
    if lopt =~ (".*" . a:flag . ".*")
        exec ('set ' . a:option . '-=' . a:flag)
    else
        exec ('set ' . a:option . '+=' . a:flag)
    endif
endfunction

" Easy autowrap toggle
function! ToggleAutoWrap()
    call ToggleFlag('formatoptions', 't')
endfunction

" Easy quit and save
nnoremap <silent> <leader>Q :qa<cr>
nnoremap <silent> <leader>q :q<cr>
nnoremap <silent> <leader>w :w<cr>
nnoremap <silent> <leader>W :wa<cr>

" Save some keystrokes
vnoremap < <gv
vnoremap > >gv
nnoremap > >>
nnoremap < <<
nnoremap ; :
vnoremap ; :
nnoremap ! :!

" Better windo (restores current window)
function! WinDo(cmd)
    let currwin=winnr()
    execute 'windo ' . a:cmd
    execute currwin . 'wincmd w'
endfunction
com! -nargs=+ -complete=command Windo call WinDo(<q-args>)

" Other shortcuts for fn keys
nnoremap <silent> <F1> :YcmRestartServer<cr>
nnoremap <silent> <F2> :set invspell<cr>
nnoremap <silent> <F3> :set invpaste<cr>
nnoremap <silent> <F4> :Windo set scrollbind!<cr>
nnoremap <silent> <F5> :redraw!<cr>

" Disable Ex mode
map Q <nop>

" I don't anticpate ever using Modula-2, but I do use *.md for markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
