#!/bin/bash

# Create file to be used for swap
sudo fallocate -l 1G /mnt/1GB.swap
# Format the file for swap
sudo mkswap /mnt/1GB.swap
# Add the file to system as swap file
sudo swapon /mnt/1GB.swap
# Check that the swap file was created
sudo swapon -s
