#!/bin/bash

pkg update -y
pkg upgrade -y

sed 's:#.*$::g' $HOME/dot/termux-packages | xargs pkg install -y
pkg autoclean -y

sed 's:#.*$::g' $HOME/dot/termux-pip-packages | xargs pip3 install

sed 's:#.*$::g' $HOME/dot/npm-packages | xargs npm install -g --ignore-scripts
