#!/bin/bash
pkg update
pkg upgrade
pkg install x11-repo -y
sed 's:#.*$::g' $HOME/dot/termux-packages | xargs pkg install -y
pkg autoclean -y

sed 's:#.*$::g' $HOME/dot/termux-packages | xargs pip install
