# If not running interactively, don't do anything else
[ -z "$PS1" ] && return

# Add a few things to paths
export PATH=~/.local/bin:$PATH
export GOPATH="$HOME/go"

# Remove terminal scroll locking
stty -ixon

# Add color to a grep commands
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rgrep='rgrep --color=auto'

# Some ls aliases
alias ls='ls --color=auto -h'
alias lal='ls -alh'
alias lla='ls -lah'
alias ll='ls -lh'
alias la='ls -ah'
alias l='ls'

# I always want color
[ -z "$TMUX" ] && export TERM="xterm-256color"

# All other cli editors suck
export EDITOR="vim"
alias vi=vim
alias vim="vim -O"

# I always seem to ls right after things like cd and clear
function cd() {
    builtin cd "$@" && ls
}
function clear() {
    /usr/bin/env clear
    ls
}

# Setup prompt
PS1="\u@\h:\W$ \[\e]2;\u@\H \w\a\]"

# Make bash history a bit more useful
HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s extglob
PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"
HISTIGNORE="ls@( *|):ll@( *|):la@( *|):cd@( *|):clear:vim:git st"
HISTSIZE=1000000
HISTFILESIZE=1000000

# Check the window size after each command and update values LINES and COLUMNS
shopt -s checkwinsize

# The pattern "**" used in pathnames will match all files in subdirectories
shopt -s globstar

# Make less more friendly for non-text input files
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# One last alias for my most commonly used tmux session
alias foobar="tmux attach -dt foobar || tmux new -s foobar"

# Make it easier to define machine-specific stuff for work
if [ -f $HOME/.bashrc_extras ]; then
    source $HOME/.bashrc_extras
fi
