" First, be iMproved
set nocompatible

" Plugins load faster with this off
filetype off

" Load plugins, either using machine-specific vimrc_plug, or using my defaults
if filereadable(expand('~/.vimrc_plug'))
    source ~/.vimrc_plug
else
    call plug#begin()
    Plug 'SirVer/ultisnips'
    Plug 'Yggdroot/indentLine'
    Plug 'christoomey/vim-tmux-navigator'
    Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
    Plug 'jefflund/cterm16'
    Plug 'jefflund/vtzoom'
    Plug 'kana/vim-arpeggio'
    Plug 'kien/ctrlp.vim'
    Plug 'majutsushi/tagbar'
    Plug 'preservim/nerdcommenter'
    Plug 'preservim/nerdtree'
    Plug 'psf/black', { 'branch': 'stable' }
    Plug 'tpope/vim-repeat'
    Plug 'ycm-core/YouCompleteMe', { 'do': 'python3 install.py --go-completer' }
    call plug#end()
endif

" Turn on file type based options
syntax on
filetype on
filetype indent on
filetype plugin on
let g:tex_flavor="latex"

" Turn on a few more options
set backspace=2
set colorcolumn=81
set guioptions=ace
set number
set relativenumber
set scrolloff=2
set showcmd
set showmode
set title
set ttyfast
set visualbell
set wrap

" Even more options for vsplits
set winwidth=84
autocmd WinEnter * setlocal number relativenumber wrap
autocmd WinLeave * setlocal nonumber norelativenumber nowrap

" Let zoom fullscreen
set winminheight=0
set winminwidth=0

" In memory buffers
set nobackup
set noswapfile
set hidden

" Switch up the colors
set t_Co=256
set t_ut=
colorscheme cterm16-foundry

" Setup statusline
set laststatus=2
set statusline=%<
set statusline+=%t
set statusline+=\ %([%Y%R%H%W]%)
set statusline+=%m
set statusline+=\ %{&spell?\"SPELL\ \":\"\"}
set statusline+=%{&paste?\"PASTE\ \":\"\"}
set statusline+=%{&scrollbind?\"SCROLLBIND\":\"\"}
set statusline+=%=
set statusline+=%-14.(%l,%v%)
set statusline+=\ %P

" Setup cursorline
autocmd WinEnter * setlocal cursorline
autocmd BufEnter * setlocal cursorline
autocmd WinLeave * setlocal nocursorline
setlocal cursorline

" Autoreload
set autoread
autocmd CursorHold * checktime

" More sane split openings
set splitbelow
set splitright

" Set the leader keys
let mapleader=" "
let maplocalleader="-"

" Better whitespace
set list listchars=tab:»\ ,trail:•,nbsp:•
set expandtab
set textwidth=79
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent

" Handle trailing whitespace
function! StripTrailingWhitespace()
    let l:win = winsaveview()
    execute '%s/\(\s\|\)\+$//e'
    call winrestview(l:win)
endfunction
nnoremap <silent> <leader><space> :call StripTrailingWhitespace()<cr>

" Setup search
set hlsearch
set incsearch
set ignorecase
set smartcase
nnoremap <silent> <leader>/ :nohlsearch<cr>

" Setup NERDTree
nnoremap <silent> <leader>n :NERDTreeToggle<cr>
let NERDTreeIgnore=[]
let NERDTreeIgnore+=['\.pyc$', '__pycache__']
let NERDTreeIgnore+=['\.o$', '\.d$']
let NERDTreeIgnore+=['\.aux$', '\.log$']
let NERDTreeIgnore+=['\.class$']
let NERDTreeIgnore+=['\.make$', '\.blg$', '\.bbl$', '\.fls$', '\.cookie$']
let NERDTreeIgnore+=['\.temp$']
let NERDTreeIgnore+=['\.lof$', '\.lol$', '\.lot$', '\.out$', '\.toc$']
let NERDTreeQuitOnOpen=1
let NERDTreeChDirMode=2
let NERDTreeDirArrowExpandable = '+'
let NERDTreeDirArrowCollapsible = '-'

" Setup CtrlP
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/]\.(git|hg|svn)$',
    \ 'file': '\v\.(pyc|blg|bbl|fls|cookies|make|o|d|class|aux|log)$',
    \ }
let g:ctrlp_working_path_mode = 'a'

" Setup YouCompleteMe
 let g:ycm_autoclose_preview_window_after_insertion=1
 let g:ycm_key_list_select_completion=['<c-n>', '<down>']
 let g:ycm_key_list_previous_completion=['<c-p>', '<up>']

" Setup UltiSnips
let g:UltiSnipsSnippetsDir="~/.vim/ultisnips"
let g:UltiSnipsSnippetDirectories = ['ultisnips']
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

" Setup Tagbar
nnoremap <silent> <leader>t :TagbarToggle<cr>
let g:tagbar_crags_bin='/usr/bin/ctags-universal'
let g:tagbar_autoclose=1
let g:tagbar_left=1
let g:tagbar_sort=0
let g:tagbar_iconchars = ['+', '-']

" Setup vim-tmux-navigator
let g:tmux_navigator_no_mappings=1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>

" Setup vim-go
let g:go_template_autocreate=0
let g:go_snippet_engine=""
let g:go_doc_keywordprg_enabled=0

" Setup vim-arpeggio
call arpeggio#load()
Arpeggio noremap jk <esc>
Arpeggio noremap! jk <esc>

" Setup Black
autocmd BufWritePre *.py silent Black
let g:black_use_virtualenv=0

" Setup indentLine
let g:indentLine_char='┆'

" Navigation shortcuts
nnoremap <s-j> <c-f>zz
nnoremap <s-k> <c-u>zz
vnoremap <s-j> <c-f>zz
vnoremap <s-k> <c-u>zz
nnoremap j gj
nnoremap k gk

" Easy quit and save
nnoremap <silent> <leader>Q :qa<cr>
nnoremap <silent> <leader>q :q<cr>
nnoremap <silent> <leader>w :w<cr>
nnoremap <silent> <leader>W :wa<cr>

" Some macro shortcuts
nnoremap <silent> <leader>~ :set paste<cr>qa
nnoremap <silent> <esc><esc> q
nnoremap <silent> <leader>` @a

" Save some keystrokes
vnoremap < <gv
vnoremap > >gv
nnoremap > >>
nnoremap < <<
nnoremap ; :
vnoremap ; :
nnoremap ! :!
nnoremap * g*
nnoremap # g#

" Make & highlight current word (like * or #, except cursor stays put)
nnoremap <silent> & :let searchTerm = '\v<'.expand("<cword>").'>' <bar> let @/ = searchTerm <bar> echo '/'.@/ <bar> call histadd("search", searchTerm) <bar> set hls<cr>

" Other handy shortcuts
nnoremap <silent> <leader>1 :YcmRestartServer<cr>
nnoremap <silent> <leader>2 :set invspell<cr>
nnoremap <silent> <leader>3 :set invpaste<cr>
nnoremap <silent> <leader>5 :redraw!<cr>
vnoremap <silent> <leader>s :sort<cr>

" Disable Ex mode
map Q <nop>

" Optionally load machine-specific vimrc_extras.
if filereadable(expand('~/.vimrc_extras'))
    source ~/.vimrc_extras
endif
